server.port=8181
spring.application.name=api-gateway

eureka.client.service-url.defaultZone=${EUREKA_URL:http://localhost:8761/eureka/}
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

jwt.secret=${JWT_SECRET} 
spring.cloud.gateway.routes[0].id=auth-service
spring.cloud.gateway.routes[0].uri=lb://AUTH-SERVICE
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/auth/**
spring.cloud.gateway.routes[0].filters[0]=StripPrefix=1

spring.cloud.gateway.default-filters[0]=DedupeResponseHeader=Access-Control-Allow-Origin RETAIN_FIRST
spring.cloud.gateway.default-filters[1]=DedupeResponseHeader=Access-Control-Allow-Methods RETAIN_FIRST
spring.cloud.gateway.default-filters[2]=DedupeResponseHeader=Access-Control-Allow-Headers RETAIN_FIRST
spring.cloud.gateway.routes[1].id=user-service
spring.cloud.gateway.routes[1].uri=lb://USER-SERVICE
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/users/**
spring.cloud.gateway.routes[1].filters[0]=StripPrefix=1

spring.cloud.gateway.routes[2].id=site-service
spring.cloud.gateway.routes[2].uri=lb://SITE-SERVICE
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/sites/**
spring.cloud.gateway.routes[2].filters[0]=StripPrefix=1

spring.cloud.gateway.routes[3].id=booking-service
spring.cloud.gateway.routes[3].uri=lb://BOOKING-SERVICE
spring.cloud.gateway.routes[3].predicates[0]=Path=/api/bookings/**
spring.cloud.gateway.routes[3].filters[0]=StripPrefix=1

spring.cloud.gateway.routes[4].id=chat-service
spring.cloud.gateway.routes[4].uri=lb://CHAT-SERVICE
spring.cloud.gateway.routes[4].predicates[0]=Path=/api/chat/**
spring.cloud.gateway.routes[4].filters[0]=StripPrefix=1

spring.cloud.gateway.routes[5].id=analytics-service
spring.cloud.gateway.routes[5].uri=lb://ANALYTICS-SERVICE
spring.cloud.gateway.routes[5].predicates[0]=Path=/api/analytics/**
spring.cloud.gateway.routes[5].filters[0]=StripPrefix=1

spring.cloud.gateway.routes[6].id=image-service
spring.cloud.gateway.routes[6].uri=lb://IMAGE-SERVICE
spring.cloud.gateway.routes[6].predicates[0]=Path=/api/images/**
spring.cloud.gateway.routes[6].filters[0]=StripPrefix=1

spring.cloud.gateway.routes[7].id=notification-service
spring.cloud.gateway.routes[7].uri=lb://NOTIFICATION-SERVICE
spring.cloud.gateway.routes[7].predicates[0]=Path=/api/notifications/**
spring.cloud.gateway.routes[7].filters[0]=StripPrefix=1
spring.cloud.gateway.routes[8].id=auth-oauth2
spring.cloud.gateway.routes[8].uri=lb://AUTH-SERVICE
spring.cloud.gateway.routes[8].predicates[0]=Path=/oauth2/**

spring.cloud.gateway.routes[9].id=auth-login-oauth2
spring.cloud.gateway.routes[9].uri=lb://AUTH-SERVICE
spring.cloud.gateway.routes[9].predicates[0]=Path=/login/oauth2/**
logging.level.org.springframework=INFO
logging.level.com.travelmgmt=DEBUG