server.port=8087
spring.application.name=image-service

spring.data.mongodb.uri=${DB_URL}
spring.data.mongodb.database=travelmgmt

eureka.client.service-url.defaultZone=${EUREKA_URL:http://localhost:8761/eureka/}
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

jwt.secret=${JWT_SECRET}
jwt.expiration=86400000

spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB

spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration

logging.level.org.springframework=INFO
logging.level.com.travelmgmt=DEBUG