server.port=8083
spring.application.name=site-service
spring.data.mongodb.uri=${DB_URL}
spring.data.mongodb.database=travelmgmt
eureka.client.service-url.defaultZone=${EUREKA_URL:http://localhost:8761/eureka/}
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
jwt.secret=7a35e86a870da6d8ea2973554a4cb2f86d881c631a59aee3da73ea49fd228f8e
jwt.expiration=86400000
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration
logging.level.org.springframework=INFO
logging.level.com.travelmgmt=DEBUG